### ISSUE TITLE
Missing subpackages

### ISSUE THREAD

**Issue by sethgrid** [tpng/gopkgs#4]
I am not seeing subpackages included in the `gopkgs` command that are seen with the `go list all` command. 

I ran into this using VSCode and opened an issue with them (https://github.com/Microsoft/vscode-go/issues/521); it appears they leverage `gopkgs`. 

I created a repo to illustrate the issue I was facing with VSCode here: https://github.com/sethgrid/vscode_autocomplete_issue

I believe that it should show a repro case for `gopkgs` too. When I `cd` into that directory, and do `gopkgs | grep sethgrid`, I do not see `subone` or `subtwo`. However, I do see those if I `go list all | grep sethgrid`.

**Comment by tpng** [comment]
Have you `go install`ed the sub packages too? Since gopkgs will only list packages that are in the `$GOPATH/pkg` folder.

You will have to run either `go get github.com/sethgrid/vscode_autocomplete_issue/...` or `go install github.com/sethgrid/vscode_autocomplete_issue/...` (the 3 dots in the end means install the subpackages too).

**Comment by sethgrid** [comment]
You can see in the latest update at https://github.com/Microsoft/vscode-go/issues/521 that the issue I faced was due to my files not yet being in the pkg dir, but only in my src dir. Maybe that makes this a non-issue for `gopkgs`?

[EDIT] I posted ^^ without refreshing the page and missed your post from 2 hours ago (facepalm). You are correct, the issue is needing to run `go install` or `go get`. Thanks!
